ftdieeprom: add stdint definition
FIX:
 x86_64-poky-linux-gcc  -m64 -march=btver1 -mtune=btver1
 --sysroot=/home/ricardo/curro/qt5022/build-qt5022/build/tmp/sysroots/qt5022
 -O2 -pipe -g -feliminate-unused-debug-types  -Wl,-O1
 -Wl,--hash-style=gnu -Wl,--as-needed  ftdieeprom.c   -o ftdieeprom
 | ftdieeprom.c: In function 'fix_csum':
 | ftdieeprom.c:36:2: error: unknown type name 'uint16_t'
 |   uint16_t csum=0xaaaa;
 |   ^
 | ftdieeprom.c:37:2: error: unknown type name 'uint16_t'
 |   uint16_t old_csum=eeprom[len-1]<<8 | eeprom[len-2];
 |   ^
 | ftdieeprom.c:40:3: error: unknown type name 'uint16_t'
 |    uint16_t value;
 |    ^
 | <builtin>: recipe for target 'ftdieeprom' failed